sudo: true
language: haskell
git:
  submodules: false
branches:
  only:
    - master
cabal: "3.0"
cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
matrix:
  include:
  - ghc: 8.6.5
notifications:
  email: false

install:
  - |
    ghc --version
    cabal --version
    cabal update
    cabal build --enable-tests --enable-benchmarks

script:
  - cabal test
